import asyncio
import os
import dotenv
dotenv.load_dotenv()
from app.database import engine
from sqlalchemy import text

async def main():
    tables = [
        "conversations",
        "chat_messages",
        "chat_message_attachments",
        "mcp_servers",
        "sql_sandbox_versions"
    ]
    async with engine.begin() as conn:
        for table in tables:
            try:
                # Oracle 12.2+ feature to start with max value
                await conn.execute(text(f"ALTER TABLE {table} MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))"))
                print(f"Successfully altered {table} ID column.")
            except Exception as e:
                print(f"Error on {table}: {e}")

asyncio.run(main())
